import { Component } from "@angular/core";

@Component({
  selector: "app-ranking",
  standalone: true,
  imports: [],
  templateUrl: "./ranking.component.html",
  styleUrl: "./ranking.component.scss",
})
export class RankingComponent {
  RankingItems = [
    {
      id: 1,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: " Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 2,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: " Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 3,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 4,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 5,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 6,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 7,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 8,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 9,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 10,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 11,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
    {
      id: 12,
      rollNo: "56",
      icon: "/assets/top-restaurant.jpg",
      name: "Maxico Drill",
      qualified: "9.5",
      Reactions: "3.5M",
      Followers: "20.9k",
    },
  ];
}
